// Do not edit this file, it is auto-patched from a central template.
import '@nti/style-common/variables.css';
import '@nti/style-common/all.scss';

export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
}

